(() => {
'use strict';
const defaults={left:['ArrowLeft'],right:['ArrowRight','KeyD'],up:['ArrowUp','KeyW'],down:['ArrowDown','KeyS'],attack:['KeyA','KeyJ'],kick:['KeyX','KeyU'],jump:['Space'],dodge:['KeyL','ShiftLeft','ShiftRight'],spell:['KeyQ','KeyE'],chi:['KeyB','KeyK'],weapon:['KeyC'],magic:['KeyV'],pause:['KeyP'],fullscreen:['KeyF']};
const labels={left:'שמאלה',right:'ימינה',up:'למעלה',down:'למטה',attack:'מכה',kick:'בעיטה',jump:'קפיצה',dodge:'גלגול',spell:'קסם',chi:'צ׳י',weapon:'החלפת נשק',magic:'החלפת קסם',pause:'השהיה',fullscreen:'מסך מלא'};
let custom={},waiting=null;
try{const saved=JSON.parse(localStorage.getItem('monk-keys-v1'));if(saved&&typeof saved==='object')for(const action of Object.keys(defaults))if(typeof saved[action]==='string'&&/^(Key[A-Z]|Digit[0-9]|Arrow(Left|Right|Up|Down)|Space|Shift(Left|Right)|Control(Left|Right)|Alt(Left|Right)|Tab|Backspace|Numpad[0-9])$/.test(saved[action]))custom[action]=saved[action];}catch{}
const keys=action=>custom[action]?[custom[action]]:defaults[action];
const action=code=>Object.keys(defaults).find(name=>keys(name).includes(code));
const name=code=>({Space:'רווח',ArrowLeft:'←',ArrowRight:'→',ArrowUp:'↑',ArrowDown:'↓',ShiftLeft:'Shift שמאל',ShiftRight:'Shift ימין',ControlLeft:'Ctrl שמאל',ControlRight:'Ctrl ימין',AltLeft:'Alt שמאל',AltRight:'Alt ימין',Backspace:'⌫'}[code]||code.replace(/^Key|^Digit/,''));
function save(){try{localStorage.setItem('monk-keys-v1',JSON.stringify(custom));}catch{}refresh();}
function set(binding,code){if(!defaults[binding]||!/^(Key[A-Z]|Digit[0-9]|Arrow(Left|Right|Up|Down)|Space|Shift(Left|Right)|Control(Left|Right)|Alt(Left|Right)|Tab|Backspace|Numpad[0-9])$/.test(code))return false;const occupied=action(code);if(occupied&&occupied!==binding)return false;custom[binding]=code;save();return true;}
function refresh(){document.querySelectorAll('[data-key] small').forEach(el=>{const binding=el.parentElement.dataset.key;el.textContent=name(keys(binding)[0]);});const bar=document.querySelector('.controls');if(bar){bar.replaceChildren();const title=document.createElement('span');title.className='controls-title';title.textContent='הדרך בידיים שלך';bar.append(title);for(const binding of ['attack','kick','jump','spell','dodge','pause']){const span=document.createElement('span'),kbd=document.createElement('kbd');kbd.textContent=keys(binding).map(name).join(' / ');span.append(kbd,' '+labels[binding]);bar.append(span);}}}
function panel(){const box=document.createElement('section');box.className='key-settings';const title=document.createElement('h3');title.textContent='מקשים במחשב';const hint=document.createElement('p');hint.className='sheet-hint';hint.textContent='לחץ על פעולה ואז הקש מקש חדש. הבחירה נשמרת בדפדפן. Escape מבטל בחירה; Enter ו־Escape שמורים לתפריטים. בנייד משתמשים בכפתורי מגע.';const grid=document.createElement('div');grid.className='key-grid';const status=document.createElement('p');status.className='key-status';status.setAttribute('role','status');function draw(){grid.replaceChildren();for(const binding of Object.keys(defaults)){const button=document.createElement('button');button.className='key-binding';const label=document.createElement('span'),key=document.createElement('kbd');label.textContent=labels[binding];key.textContent=keys(binding).map(name).join(' / ');button.append(label,key);button.onclick=()=>{waiting={binding,draw,status};draw();button.classList.add('selected');status.textContent=`בחר מקש עבור ${labels[binding]}`;};grid.append(button);}}draw();const reset=document.createElement('button');reset.className='menu-link';reset.textContent='איפוס מקשים לברירת המחדל';reset.onclick=()=>{waiting=null;custom={};save();draw();status.textContent='המקשים אופסו';};box.append(title,hint,grid,status,reset);return box;}
addEventListener('keydown',event=>{if(!waiting)return;if(document.getElementById('menu-sheet').hidden){waiting=null;return;}event.preventDefault();event.stopImmediatePropagation();if(event.repeat)return;const pending=waiting;if(event.code==='Escape'){waiting=null;pending.draw();pending.status.textContent='הבחירה בוטלה';return;}if(set(pending.binding,event.code)){waiting=null;pending.draw();pending.status.textContent=`${labels[pending.binding]}: ${name(event.code)} — נשמר`;}else pending.status.textContent='המקש כבר משויך לפעולה אחרת או שמור לתפריט. בחר מקש אחר.';},true);
window.MonkControls={action,keys,name,panel,set,reset:()=>{custom={};save();},bindings:()=>Object.fromEntries(Object.keys(defaults).map(k=>[k,[...keys(k)]])),refresh,cancel:()=>{waiting=null;}};
})();
