(() => {
'use strict';
const D=window.MonkContent,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b)=>Math.hypot(a.x-b.x,(a.y-b.y)*1.5);
const held=new Set(),pointers=new Map(),lastTap=new Map();
let runDirection=null,stageElapsed=0,lastTimeBonus=0;
const timeBonus=()=>Math.floor(12000/(1+stageElapsed/90));
function press(action){if(!held.has(action)&&['left','right','up','down'].includes(action)){const previous=lastTap.get(action);runDirection=previous!==undefined&&time-previous<=.28?action:null;lastTap.set(action,time);}held.add(action);}
function release(action){held.delete(action);if(runDirection===action)runDirection=null;}
let W=1067,H=600,mode='title',level=0,time=0,camera=0,score=0,best=0,wave=0,player=null;
let enemies=[],drops=[],chests=[],projectiles=[],hazards=[],effects=[],bossSpawned=false;
let combo=0,comboTime=0,comboName='',hitStop=0,shake=0,toastTime=0,saveTimer=0,nextId=1;
let difficulty='warrior',audio=null,muted=false,lastFrame=0,manual=false;
let profile={version:3,unlocked:1,difficulty:'warrior',save:null,checkpoint:null};
const chapter=()=>D.chapters[level],world=()=>D.worlds[chapter().world],length=()=>chapter().length;
const tuning=()=>({story:{hp:.72,damage:.6,speed:.88},warrior:{hp:1,damage:1,speed:1},master:{hp:1.32,damage:1.4,speed:1.14}}[difficulty]);
function validCheckpoint(c){return c&&Number.isInteger(c.level)&&c.level>=0&&c.level<15&&c.level%3===0&&c.player&&Number.isFinite(c.player.hp)&&Number.isFinite(c.player.x)&&['story','warrior','master'].includes(c.difficulty);}
function validSave(s){return s&&Number.isInteger(s.level)&&s.level>=0&&s.level<15&&s.player&&s.player.lives>0&&Number.isFinite(s.player.x)&&Number.isFinite(s.player.hp)&&Array.isArray(s.enemies)&&Array.isArray(s.drops)&&['stage','battle'].includes(s.kind);}
try{
 const raw=localStorage.getItem('monk-profile-v3');
 if(raw){const p=JSON.parse(raw);profile.unlocked=Number.isInteger(p.unlocked)?clamp(p.unlocked,1,15):1;profile.difficulty=['story','warrior','master'].includes(p.difficulty)?p.difficulty:'warrior';profile.save=validSave(p.save)?p.save:null;if(validCheckpoint(p.checkpoint))profile.checkpoint=p.checkpoint;}
 else{const p=JSON.parse(localStorage.getItem('monk-profile-v2'));if(p){profile.unlocked=Number.isInteger(p.unlocked)?clamp((p.unlocked-1)*3+1,1,15):1;profile.difficulty=['story','warrior','master'].includes(p.difficulty)?p.difficulty:'warrior';if(p.save){const s={...p.save,level:p.save.level*3,legacy:true};if(validSave(s))profile.save=s;}}}
 best=Number(localStorage.getItem('monk-best'))||0;
}catch{}
difficulty=profile.difficulty;
function store(){try{localStorage.setItem('monk-profile-v3',JSON.stringify(profile));}catch{}window.refreshPremiumMenu?.();}
function saveRun(){if(!player||!['playing','paused','stageclear'].includes(mode))return;profile.save={kind:mode==='stageclear'?'stage':'battle',level:mode==='stageclear'?level+1:level,score,combatVersion:2,stageElapsed:mode==='stageclear'?0:stageElapsed,difficulty,player:{...player},enemies:enemies.filter(e=>!e.remove).map(e=>({...e})),drops:drops.filter(d=>d.life>0).map(d=>({...d})),chests:chests.map(c=>({...c})),projectiles:projectiles.filter(p=>p.life>0).map(p=>({...p})),hazards:hazards.filter(h=>h.life>0).map(h=>({...h})),wave,bossSpawned,nextId};store();}
function newPlayer(){return {x:100,y:465,z:0,vz:0,dir:1,hp:120,maxHP:120,healthVersion:1,chi:75,mana:100,lives:difficulty==='story'?5:3,attack:0,kick:0,cooldown:0,inv:1.5,jumpCD:0,special:0,dodge:0,dodgeCD:0,castCD:0,shield:0,shieldTime:0,slow:0,fury:0,haste:0,weapon:'staff',weapons:['staff'],spell:null,spells:[],spellRanks:{},history:[],lastAction:'kick',rank:1,xp:0,gold:0};}
function normalizePlayer(p){const a={...newPlayer(),...p};if(!p.healthVersion){a.maxHP=(Number.isFinite(p.maxHP)?p.maxHP:100)+20;a.hp=Math.min(a.maxHP,(Number.isFinite(p.hp)?p.hp:100)+20);}a.healthVersion=1;a.weapons=(p.weapons||['staff']).filter(k=>D.weapons[k]);if(!a.weapons.length)a.weapons=['staff'];a.weapon=a.weapons.includes(p.weapon)?p.weapon:a.weapons[0];a.spells=(p.spells||[]).filter(k=>D.spells[k]);a.spell=a.spells.includes(p.spell)?p.spell:a.spells[0]||null;a.spellRanks=p.spellRanks||{};a.mana=clamp(Number.isFinite(p.mana)?p.mana:100,0,100);a.history=[];for(const k of ['attack','kick','dodge','special'])a[k]=0;a.inv=1.5;return a;}
function tone(f,d=.1,type='triangle',volume=.025){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,f*.4),audio.currentTime+d);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function initAudio(){try{audio ||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function toast(){ $('toast').hidden=true; }
const touchVisible=()=>matchMedia('(pointer:coarse)').matches||W<680;
function clearInput(){held.clear();pointers.clear();lastTap.clear();runDirection=null;document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
function checkpointPlayer(p){const a=normalizePlayer(JSON.parse(JSON.stringify(p)));a.hp=a.maxHP;a.chi=100;a.mana=100;a.lives=difficulty==='story'?5:3;a.shield=0;a.shieldTime=0;a.slow=0;a.fury=0;a.haste=0;return a;}
function saveWorldCheckpoint(at){profile.checkpoint={level:Math.floor(at/3)*3,score,difficulty,player:checkpointPlayer(player)};}
function checkpointSave(){const c=profile.checkpoint;return {kind:'stage',level:c.level,score:c.score,combatVersion:2,difficulty:c.difficulty,player:checkpointPlayer(c.player),enemies:[],drops:[],chests:[],projectiles:[],hazards:[],wave:0,bossSpawned:false};}
function start(at=0){initAudio();difficulty=profile.difficulty;level=at;score=0;player=newPlayer();saveWorldCheckpoint(at);loadStage();}
function makeChest(x,index){const gear=['spear','chain','ember','hammer'][level%4],magic=['fire','frost','lightning','earth'][(level+index)%4];return {id:nextId++,x,y:index%2?510:435,hp:24,opened:false,items:index===0?[{type:'spell',key:magic},{type:'chi'}]:index===1?[{type:'weapon',key:gear},{type:'hp'}]:index===2?[{type:'spell',key:magic},{type:'relic',key:level%2?'haste':'fury'}]:[{type:'gold'},{type:'hp'}]};}
function loadStage(){if(!validCheckpoint(profile.checkpoint)||profile.checkpoint.level!==Math.floor(level/3)*3)saveWorldCheckpoint(level);if(level%3===0){player=checkpointPlayer(player);}mode='playing';stageElapsed=0;lastTimeBonus=0;player.x=100;player.y=465;player.z=0;player.vz=0;player.hp=Math.min(player.maxHP,player.hp+35);player.chi=Math.min(100,player.chi+25);player.inv=1.5;for(const k of ['attack','kick','cooldown','dodge','dodgeCD','castCD','special'])player[k]=0;player.history=[];
 camera=0;wave=0;bossSpawned=false;enemies=[];drops=[];effects=[];projectiles=[];hazards=[];hitStop=0;saveTimer=0;chests=[580,1400,2450,3600].map((x,i)=>makeChest(x*length()/4400,i));clearInput();$('title-screen').hidden=true;$('modal').hidden=true;$('menu-sheet').hidden=true;for(const id of ['hud','loadout-hud','journey-progress'])$(id).hidden=false;$('touch-controls').hidden=!touchVisible();$('boss-hud').hidden=true;document.querySelectorAll('.chapter').forEach((el,i)=>{el.classList.toggle('active',i===chapter().world);el.classList.toggle('done',profile.unlocked>i*3+3);});spawnWave();toast(`${world().name} · ${chapter().name}`,2.5);updateHUD();saveRun();}
function resume(){const s=profile.save;if(!s)return;initAudio();difficulty=['story','warrior','master'].includes(s.difficulty)?s.difficulty:'warrior';level=s.level;score=s.score||0;player=normalizePlayer(s.player);if(s.kind==='stage'||s.legacy){loadStage();return;}const saved=normalizePlayer(s.player);loadStage();player=saved;stageElapsed=Number.isFinite(s.stageElapsed)?Math.max(0,s.stageElapsed):0;enemies=s.enemies.map(e=>{const a={...e};if((s.combatVersion||0)<2){if(a.boss)a.rank=D.bosses[a.bossId].rank;else a.rank=clamp(Math.max(a.rank||1,1+Math.floor(level/3)),1,5);const target=a.boss?Math.round(D.bosses[a.bossId].hp*tuning().hp):Math.round(D.enemies[a.type].hp*(1+(a.rank-1)*.38)*tuning().hp);a.hp=a.dead?0:Math.max(1,Math.round(target*clamp(a.hp/a.maxHP,0,1)));a.maxHP=target;a.damage=a.boss?D.bosses[a.bossId].damage:D.enemies[a.type].damage+a.rank*2;a.speed=a.boss?(58+level*2)*tuning().speed*1.12:D.enemies[a.type].speed*tuning().speed*(1+(a.rank-1)*.07);}return a;});drops=s.drops.map(d=>({...d}));chests=s.chests||chests;projectiles=s.projectiles||[];hazards=s.hazards||[];wave=s.wave;bossSpawned=s.bossSpawned;nextId=s.nextId||1000;camera=clamp(player.x-W*.35,0,length()-W);saveRun();updateHUD();toast('המסע ממשיך',1.5);}
function enemy(type,x,y,rank=1){const a=D.enemies[type],d=tuning(),hp=Math.round(a.hp*(1+(rank-1)*.38)*d.hp);return {id:nextId++,type,rank,x:clamp(x,80,length()-130),y:clamp(y,380,540),hp,maxHP:hp,dir:-1,boss:false,cooldown:.9+Math.random(),wind:0,attack:0,stun:0,flash:0,dead:0,slow:0,burn:0,burnTick:.5,speed:a.speed*d.speed*(1+(rank-1)*.07),damage:a.damage+rank*2,guard:0,offset:(nextId%3-1)*16};}
function spawnWave(){wave++;const pool=level<2?['grunt','scout','shield']:level<5?['grunt','scout','archer','brute']:['grunt','scout','brute','shield','archer','shaman','berserker'];const count=3+Math.min(3,Math.floor(level/3))+(wave===4?1:0);for(let i=0;i<count;i++){const type=pool[(i+wave+level)%pool.length],rank=clamp(1+Math.floor(level/3)+(i%3===0?1:0),1,5);enemies.push(enemy(type,player.x+260+i*70,398+(i%3)*48,rank));}toast(`מארב ${wave} מתוך ${chapter().waves}`,1.2);}
function spawnBoss(){bossSpawned=true;const b=chapter().boss,hp=Math.round(b.hp*tuning().hp);enemies.push({...enemy('brute',length()-220,465,3),boss:true,bossId:b.id,rank:b.rank,hp,maxHP:hp,speed:(58+level*2)*tuning().speed*1.12,damage:b.damage,cooldown:1.4,phase:0,skill:null,guard:0});toast(b.name,2.8);tone(85,.55,'sawtooth',.035);saveRun();}
function showModal(k,title,message,button){$('modal-kicker').textContent=k;$('modal-title').textContent=title;$('modal-text').textContent=message+(mode==='stageclear'||mode==='win'?`\nזמן: ${Math.floor(stageElapsed/60)}:${String(Math.floor(stageElapsed%60)).padStart(2,'0')} · בונוס מהירות: +${lastTimeBonus.toLocaleString('he-IL')}`:'');$('continue-btn').textContent=button;$('modal').hidden=false;$('touch-controls').hidden=true;clearInput();}
function pause(){if(mode==='playing'){mode='paused';saveRun();showModal('PAUSE','רגע לנשום','הקרב, הציוד והקסמים נשמרו.','חזרה לקרב');}else if(mode==='paused'){mode='playing';$('modal').hidden=true;$('touch-controls').hidden=!touchVisible();}}
function saveBest(){best=Math.max(best,score);$('best-score').textContent=String(best).padStart(6,'0');try{localStorage.setItem('monk-best',best);}catch{}}
function stageClear(){lastTimeBonus=timeBonus();score+=lastTimeBonus;profile.unlocked=Math.max(profile.unlocked,Math.min(15,level+2));saveBest();mode=level===14?'win':'stageclear';if(mode==='win'){profile.save=null;profile.checkpoint=null;store();}else{if((level+1)%3===0)saveWorldCheckpoint(level+1);saveRun();}$('boss-hud').hidden=true;const next=D.chapters[level+1];showModal(level===14?'THE PATH IS COMPLETE':`CHAPTER ${level+1} / 15`,level===14?'כתר האפר נשבר.':'הזירה שוחררה!',level===14?`כל 15 הבוסים הובסו.\nניקוד סופי: ${score.toLocaleString('he-IL')}`:`${chapter().boss.name} הובס.\nהיעד הבא: ${D.worlds[next.world].name} · ${next.name}\nהנשקים והקסמים ממשיכים איתך.`,level===14?'מסע חדש':'לתת־השלב הבא ←');tone(530,.3);}
function sparkle(x,y,color,n=9){for(let i=0;i<n;i++)effects.push({type:'spark',x,y,vx:(Math.random()-.5)*230,vy:-Math.random()*160,life:.25+Math.random()*.35,col:color});}
function addDrop(x,y,item){drops.push({id:nextId++,x,y,life:35,...item});}
function gainXP(amount){player.xp+=amount;const need=90+player.rank*45;if(player.xp>=need&&player.rank<12){player.xp-=need;player.rank++;player.maxHP+=5;player.hp=Math.min(player.maxHP,player.hp+20);toast(`דרגת נזיר ${player.rank} · חיים וכוח הוגדלו`,2);sparkle(player.x,player.y-65,'#f9da9e',22);}}
function damageEnemy(e,amount,knock=0,options={}){if(e.dead)return;let damage=amount*(1+(player.rank-1)*.045);const frontal=(player.x-e.x)*e.dir>0;if(((e.type==='shield'&&!e.guardBroken)||e.guard>0)&&frontal&&!options.breakGuard)damage*=.35;if(options.breakGuard){e.guard=0;e.guardBroken=1.5;if(!options.silent)e.stun=Math.max(e.stun||0,e.boss?.18:.7);}e.hp-=Math.round(damage);e.flash=.12;if(!options.silent)e.stun=Math.max(e.stun||0,e.boss?.1:.25);e.x=clamp(e.x+player.dir*knock,e.boss?120:50,length()-(e.boss?145:60));if(!options.silent){hitStop=.035;shake=Math.max(shake,e.boss?4:2);sparkle(e.x,e.y-65,'#f3cc8d');tone(160,.065);player.chi=clamp(player.chi+damage*.12,0,100);combo++;comboTime=2;}if(e.hp<=0){e.dead=.5;score+=e.boss?900*(level+1):80+e.rank*35;player.gold+=e.boss?80:5*e.rank;gainXP(e.boss?100:15+e.rank*5);sparkle(e.x,e.y-60,world().accent,16);if(!e.boss){const r=Math.random();if(r<.18)addDrop(e.x,e.y,{type:'hp'});else if(r<.34)addDrop(e.x,e.y,{type:'chi'});else if(r<.42)addDrop(e.x,e.y,{type:'spell',key:Object.keys(D.spells)[(e.id+level)%4]});else if(r<.48)addDrop(e.x,e.y,{type:'weapon',key:Object.keys(D.weapons)[1+(e.id+level)%4]});}}}
function openChest(chest){if(chest.opened)return;chest.opened=true;chest.items.forEach((item,i)=>addDrop(chest.x+(i-.5)*34,chest.y,item));score+=75;sparkle(chest.x,chest.y-26,'#e8c894',18);tone(690,.15);}
function melee(kind){if(player.cooldown>0||player.special>0||player.dodge>0)return;const weapon=D.weapons[player.weapon];player.lastAction=kind;player.history=player.history.filter(h=>time-h.t<1.7);player.history.push({kind,t:time});if(player.history.length>3)player.history.shift();let move=D.combos.find(m=>m.keys.join(',')===player.history.map(h=>h.kind).join(','));if(kind==='kick'&&player.z>20)move={name:'בעיטת השמיים',damage:48,range:135,knock:45};if(kind==='strike'&&player.dodgeCD>.7)move={name:'מכת הצל',damage:49,range:135,knock:38};const kick=kind==='kick',range=kick?(move?.range||94):weapon.range+(move?Math.max(0,move.range-112)*.45:0),damage=kick?(move?.damage||25):weapon.damage*(move?move.damage/25:1),area=move?.area||(!kick&&player.weapon==='chain');player.attackDuration=kick?0:Math.min(.48,weapon.speed*.85);player.attack=player.attackDuration;player.kick=kick?.3:0;player.cooldown=(kick?.34:weapon.speed)*(player.haste>0?.7:1);if(move){comboName=move.name;player.cooldown+=.09;toast(move.name,.8);effects.push({type:'ring',x:player.x,y:player.y-50,life:.55,col:weapon.color});}for(const e of enemies){const dx=(e.x-player.x)*player.dir;if(!e.dead&&Math.abs(e.y-player.y)<(area?86:49)&&(area?Math.abs(dx)<range:dx>-25&&dx<range)){damageEnemy(e,damage*(player.fury>0?1.4:1),move?.knock||(kick?27:12),{breakGuard:kick||move?.breakGuard||player.weapon==='hammer'});if(!kick&&player.weapon==='ember')e.burn=3;if(!kick&&player.weapon==='hammer')e.stun=Math.max(e.stun,e.boss?.25:.65);}}for(const chest of chests)if(!chest.opened&&Math.abs(chest.y-player.y)<56&&Math.abs(chest.x-player.x)<range){chest.hp-=damage;if(chest.hp<=0)openChest(chest);}effects.push({type:'slash',x:player.x+player.dir*(kick?42:60),y:player.y-65-player.z,dir:player.dir,life:.2,col:kick?'#e9e8ca':weapon.color});tone(kick?100:310,.09);}
function dodge(){if(player.dodgeCD>0||player.z>0)return;player.dodge=.3;player.dodgeCD=1.15;player.inv=Math.max(player.inv,.42);player.attack=0;player.kick=0;tone(180,.12);}
function chi(){if(player.chi<45||player.special>0||player.cooldown>0)return;player.chi-=45;player.special=.65;player.inv=.8;player.cooldown=.7;shake=7;effects.push({type:'ring',x:player.x,y:player.y-42,life:.65,col:'#b9f4d0'});for(const e of enemies)if(!e.dead&&distance(e,player)<185)damageEnemy(e,75,45,{breakGuard:true});toast('סופת צ׳י',.7);tone(660,.4,'sawtooth',.02);}
function projectile(owner,x,y,dir,kind,damage,extra={}){const colors={arrow:'#d8c8aa',fire:'#ff9c56',frost:'#9edfe9',venom:'#a9d971',arcane:'#d5a0ee'};projectiles.push({id:nextId++,owner,x,y,vx:dir*(kind==='arrow'?330:240),vy:0,kind,damage,r:kind==='arrow'?9:17,life:4,color:colors[kind]||'#f4d098',hits:[],...extra});}
function cast(){if(player.castCD>0||player.dodge>0)return;const key=player.spell,spell=D.spells[key];if(!spell){toast('שבור תיבה כדי למצוא קסם',.8);player.castCD=.7;return;}if(player.mana<spell.cost){toast('אין מספיק צ׳י',.7);player.castCD=.6;return;}player.mana-=spell.cost;player.castCD=.85;const rank=player.spellRanks[key]||1,power=1+(rank-1)*.3;if(key==='fire')projectile('player',player.x+player.dir*35,player.y,player.dir,'fire',58*power,{vx:player.dir*400,r:22,life:2.6,pierce:true});if(key==='frost'){for(const e of enemies){const dx=(e.x-player.x)*player.dir;if(!e.dead&&dx>-20&&dx<265&&Math.abs(e.y-player.y)<86){e.slow=4;e.stun=1.2;damageEnemy(e,38*power,15,{breakGuard:true});}}effects.push({type:'ring',x:player.x+player.dir*100,y:player.y-45,life:.65,col:spell.color});}if(key==='lightning'){let origin={x:player.x,y:player.y};const targets=enemies.filter(e=>!e.dead&&distance(e,player)<450).sort((a,b)=>distance(a,player)-distance(b,player)).slice(0,3+rank);for(const e of targets){effects.push({type:'bolt',x:origin.x,y:origin.y-65,tx:e.x,ty:e.y-65,life:.35,col:spell.color});damageEnemy(e,50*power,0,{breakGuard:true});origin=e;}}if(key==='earth'){player.shield=60+rank*20;player.shieldTime=12;for(const e of enemies)if(!e.dead&&distance(e,player)<145)damageEnemy(e,32*power,25,{breakGuard:true});}toast(`${spell.name} · דרגה ${rank}`,.9);tone(740,.2,'sawtooth',.02);saveRun();}
function cycleWeapon(){if(!player?.weapons.length)return;player.weapon=player.weapons[(player.weapons.indexOf(player.weapon)+1)%player.weapons.length];toast(D.weapons[player.weapon].name,1);updateHUD();saveRun();}
function cycleSpell(){if(!player?.spells.length){toast('קסמים נמצאים בתיבות ובשלל',1);return;}player.spell=player.spells[(player.spells.indexOf(player.spell)+1)%player.spells.length];toast(D.spells[player.spell].name,1);updateHUD();saveRun();}
function pickup(d){if(d.type==='hp')player.hp=Math.min(player.maxHP,player.hp+30);else if(d.type==='chi')player.chi=Math.min(100,player.chi+35);else if(d.type==='weapon'){if(!player.weapons.includes(d.key))player.weapons.push(d.key);player.weapon=d.key;toast(`נשק: ${D.weapons[d.key].name}`,1.7);}else if(d.type==='spell'){player.mana=Math.min(100,player.mana+30);if(!player.spells.includes(d.key))player.spells.push(d.key);player.spellRanks[d.key]=Math.min(3,(player.spellRanks[d.key]||0)+1);player.spell=d.key;toast(`${D.spells[d.key].name} · דרגה ${player.spellRanks[d.key]}`,1.7);}else if(d.type==='relic'){player[d.key]=20;toast(d.key==='haste'?'קמע הרוח · מהירות ל־20 שניות':'קמע הזעם · כוח ל־20 שניות',1.7);}else if(d.type==='gold'){player.gold+=35;score+=150;}sparkle(d.x,d.y-20,'#bbdbb4',12);tone(710,.13);d.life=0;saveRun();}
function hurtPlayer(amount,from){if(player.inv>0||player.z>36||mode!=='playing')return;let damage=Math.round(amount*tuning().damage);if(player.shield>0){const absorbed=Math.min(player.shield,damage);player.shield-=absorbed;damage-=absorbed;}player.hp-=damage;player.inv=.7;player.x=clamp(player.x+(player.x>from?20:-20),25,length()-60);shake=6;combo=0;sparkle(player.x,player.y-65,player.shield>0?'#dbcf9b':'#df8e77');tone(60,.16,'sawtooth',.025);if(player.hp<=0){player.lives--;if(player.lives>0){player.hp=player.maxHP;player.inv=2.8;player.chi=Math.max(50,player.chi);toast('נשימה חדשה',1.2);}else{player.hp=0;mode='gameover';if(!validCheckpoint(profile.checkpoint)||profile.checkpoint.level!==Math.floor(level/3)*3)saveWorldCheckpoint(level);profile.save=checkpointSave();store();saveBest();showModal('WORLD CHECKPOINT','העולם מחכה לך',`נקודת השמירה: תחילת ${world().name}.\nהציוד, הדרגה והניקוד שהיו בכניסה לעולם נשמרו.\nחוזרים עם חיים מלאים ופסילות מחודשות.`,'חזרה לתחילת העולם');}}}
function hazard(x,y,r,kind,delay=.8,life=1.2,damage=16){hazards.push({id:nextId++,x:clamp(x,40,length()-40),y:clamp(y,380,540),r,kind,delay,life,damage,tick:0});}
function bossCombatPhase(e){return e.hp/e.maxHP>.7?1:e.hp/e.maxHP>.35?2:3;}
function chooseBossSkill(e){
 const b=D.bosses[e.bossId],phase=bossCombatPhase(e),dx=Math.abs(player.x-e.x),allies=enemies.filter(a=>!a.boss&&!a.dead).length;
 const choices=b.rotation.filter((skill,i,list)=>list.indexOf(skill)===i).filter(skill=>!(skill==='summon'&&allies>=4)&&!(skill==='guard'&&e.guard>0));
 const scored=choices.map(skill=>{
  let score=skill===b.rotation[e.phase%b.rotation.length]?2:0;
  if(skill===e.lastSkill)score-=20;
  if(skill==='slam')score+=dx<170?5:-4;
  if(skill==='charge')score+=dx>190?5:0;
  if(['volley','frost','lightning','meteor','poison','mines'].includes(skill))score+=dx>170?3:0;
  if(skill==='guard')score+=dx<180&&(player.attack>0||player.kick>0)?9:-2;
  if(skill==='summon')score+=allies===0&&phase>1?5:1;
  if(skill==='warcry')score+=allies>0?4:-3;
  if(skill==='pull')score+=dx>240?4:0;
  if(skill==='flame')score+=dx<240?3:0;
  if(skill==='royal')score+=phase===3?4:0;
  return {skill,score};
 }).sort((a,b)=>b.score-a.score);
 return scored[0]?.skill||b.rotation[e.phase%b.rotation.length];
}
function prepareBossAttack(e){
 e.combatPhase=bossCombatPhase(e);e.skill=chooseBossSkill(e);
 e.targetX=player.x;e.targetY=player.y;e.aimDir=Math.sign(player.x-e.x)||e.dir;
 // Commit before the warning: moving away must actually evade the attack.
 e.wind=Math.max(.62,(['meteor','mines','royal'].includes(e.skill)?1.05:.88)-(e.combatPhase-1)*.08-(e.rank-1)*.025);
}
function bossAbility(e){const b=D.bosses[e.bossId],skill=e.skill,enraged=bossCombatPhase(e)===3,targetX=e.targetX??player.x,targetY=e.targetY??player.y;e.phase=(e.phase||0)+1;e.lastSkill=skill;
 if(skill==='slam')hazard(e.x,e.y,enraged?185:135,'shock',.18,.4,e.damage+4);
 if(skill==='charge'){e.charge=.46;e.chargeDir=e.aimDir||e.dir;e.chargeY=clamp((targetY-e.y)/.46,-180,180);}
 if(skill==='volley')for(let i=-2;i<=2;i++)projectile('enemy',e.x,e.y,e.dir,'arrow',e.damage,{vy:clamp((targetY-e.y)*1.2,-100,100)+i*38,life:3});
 if(skill==='poison')for(let i=0;i<3;i++)hazard(targetX+(i-1)*75,targetY+(i-1)*25,47,'poison',.65,5,e.damage*.65);
 if(skill==='frost')for(let i=-1;i<=1;i++)projectile('enemy',e.x,e.y,e.dir,'frost',e.damage,{vy:clamp(targetY-e.y,-90,90)+i*40,r:22,life:4});
 if(skill==='summon'){if(enemies.filter(a=>!a.boss&&!a.dead).length<6)for(let i=0;i<2;i++)enemies.push(enemy(level>8?'berserker':'scout',e.x+(i?90:-90),410+i*95,clamp(1+Math.floor(level/3),1,5)));}
 if(skill==='guard'){e.guard=3.5;hazard(e.x,e.y,125,'shock',.6,.4,e.damage);}
 if(skill==='mines')for(let i=0;i<4;i++)hazard(targetX+(i-1.5)*90,400+i*35,40,'mine',1.8,3,e.damage+4);
 if(skill==='pull'){if(player.inv<=0&&player.z<36)player.x=clamp(player.x+(e.x-player.x)*.4,30,length()-60);hazard(e.x,e.y,160,'shock',.95,.5,e.damage+3);effects.push({type:'bolt',x:e.x,y:e.y-70,tx:player.x,ty:player.y-60,life:.5,col:'#a8e8e4'});}
 if(skill==='warcry'){for(const a of enemies)if(a!==e&&!a.dead){a.hp=Math.min(a.maxHP,a.hp+24);a.rage=6;}e.rage=6;hazard(e.x,e.y,205,'shock',.5,.4,e.damage*.8);}
 if(skill==='lightning')for(let i=0;i<3;i++)hazard(targetX+(i-1)*115,targetY,50,'lightning',.65+i*.2,.45,e.damage+5);
 if(skill==='meteor')for(let i=0;i<4;i++)hazard(targetX+(i-1.5)*85,390+(i%3)*55,48,'meteor',.8+i*.15,.65,e.damage+6);
 if(skill==='flame')for(let i=0;i<6;i++){const angle=i*Math.PI/3;projectile('enemy',e.x,e.y,1,'fire',e.damage,{vx:Math.cos(angle)*190,vy:Math.sin(angle)*90,life:2.6,r:20});}
 if(skill==='royal'){e.guard=2;for(let i=-1;i<=1;i++)projectile('enemy',e.x,e.y,e.dir,'arcane',e.damage+3,{vy:i*45,r:24});hazard(targetX,targetY,100,'meteor',.9,.6,e.damage+8);}
 e.recovery=enraged?.32:.48;e.cooldown=Math.max(.8,b.cooldown/(1+(bossCombatPhase(e)-1)*.16));e.attack=.35;
}
function updateEnemy(e,dt){if(e.dead){e.dead-=dt;if(e.dead<=0){e.remove=true;if(e.boss)stageClear();}return;}for(const key of ['flash','stun','slow','guard','guardBroken','rage','attack','recovery'])e[key]=Math.max(0,(e[key]||0)-dt);e.cooldown-=dt;if(!e.boss||!(e.wind>0||e.charge>0))e.dir=player.x>e.x?1:-1;if(e.burn>0){e.burn-=dt;e.burnTick-=dt;if(e.burnTick<=0){e.burnTick=.5;damageEnemy(e,7,0,{silent:true,breakGuard:true});if(e.dead)return;}}if(e.charge>0){e.charge-=dt;e.x=clamp(e.x+(e.chargeDir||e.dir)*390*dt,120,length()-145);e.y=clamp(e.y+(e.chargeY||0)*dt,380,540);if(Math.abs(player.x-e.x)<80&&Math.abs(player.y-e.y)<60)hurtPlayer(e.damage+4,e.x);return;}if(e.stun>0||e.recovery>0)return;
 if(e.wind>0){e.wind-=dt;if(e.wind<=0){if(e.boss)bossAbility(e);else{const a=D.enemies[e.type];e.attack=.32;e.cooldown=a.cooldown/(1+(e.rank-1)*.1);if(a.behavior==='ranged')projectile('enemy',e.x,e.y,e.dir,'arrow',e.damage);else if(a.behavior==='mage'){projectile('enemy',e.x,e.y,e.dir,'venom',e.damage,{r:19});for(const ally of enemies)if(!ally.boss&&distance(ally,e)<190)ally.hp=Math.min(ally.maxHP,ally.hp+12);e.cooldown=a.cooldown/(1+(e.rank-1)*.1);}else if(Math.abs(e.x-player.x)<a.range&&Math.abs(e.y-player.y)<47)hurtPlayer(e.damage,e.x);}}return;}
 const dx=player.x-e.x,dy=player.y+(e.offset||0)-e.y,def=D.enemies[e.type],ranged=!e.boss&&['ranged','mage'].includes(def.behavior);let speed=e.speed*(e.slow>0?.3:1)*(e.rage>0?1.4:1);if(e.type==='berserker'&&e.hp<e.maxHP/2)speed*=1.4;const preferred=e.boss?(D.bosses[e.bossId].weapon==='bow'?250:110):ranged?235+(e.rank-1)*10:Math.max(56,def.range-24);if(Math.abs(dx)>preferred+12)e.x+=Math.sign(dx)*speed*dt;else if(ranged&&Math.abs(dx)<165)e.x-=Math.sign(dx)*speed*.7*dt;e.x=clamp(e.x,e.boss?120:40,length()-(e.boss?145:60));if(e.boss&&e.rank>=3&&player.attack>0&&Math.abs(dx)<150&&e.cooldown>.5)e.y=clamp(e.y+(e.id%2?1:-1)*speed*.5*dt,380,540);else if(Math.abs(dy)>9)e.y=clamp(e.y+Math.sign(dy)*speed*.7*dt,380,540);if(e.cooldown<=0&&(e.boss||Math.abs(dx)<def.range+20)&&Math.abs(dy)<(e.boss?160:ranged?80:48)){if(e.boss)prepareBossAttack(e);else e.wind=Math.max(.32,(def.behavior==='quick'?.4:def.behavior==='heavy'?.85:.6)-(e.rank-1)*.035);}}
function encounterAt(index){return [0,1050,2050,3050][index]*length()/4400;}
function update(dt){time+=dt;if(mode!=='playing')return;stageElapsed+=dt;if(hitStop>0){hitStop-=dt;return;}saveTimer+=dt;if(saveTimer>2){saveRun();saveTimer=0;}shake=Math.max(0,shake-dt*25);toastTime-=dt;if(toastTime<=0)$('toast').hidden=true;comboTime-=dt;if(comboTime<=0){combo=0;comboName='';}for(const k of ['attack','kick','cooldown','inv','jumpCD','special','dodge','dodgeCD','castCD','shieldTime','slow','fury','haste'])player[k]=Math.max(0,(player[k]||0)-dt);if(player.shieldTime===0)player.shield=0;player.chi=Math.min(100,player.chi+dt*2.7);player.mana=Math.min(100,player.mana+dt*4);
 const dx=Number(held.has('right'))-Number(held.has('left')),dy=Number(held.has('down'))-Number(held.has('up')),running=runDirection&&held.has(runDirection)&&((runDirection==='right'&&dx>0)||(runDirection==='left'&&dx<0)||(runDirection==='up'&&dy<0)||(runDirection==='down'&&dy>0)),pace=(running?1.7:1)*(player.slow>0?.55:1),speed=(player.haste>0?270:230)*pace,norm=dx&&dy?.707:1;player.x=clamp(player.x+dx*speed*dt*norm,25,length()-60);player.y=clamp(player.y+dy*155*pace*dt*norm,380,540);if(dx)player.dir=dx;
 if(held.has('jump')&&player.z===0&&player.jumpCD===0){player.vz=330;player.jumpCD=.83;tone(270,.1);}if(player.z>0||player.vz>0){player.z+=player.vz*dt;player.vz-=790*dt;if(player.z<=0){player.z=0;player.vz=0;}}if(held.has('dodge'))dodge();if(player.dodge>0)player.x=clamp(player.x+player.dir*445*dt,25,length()-60);if(held.has('attack')||held.has('kick'))melee(held.has('attack')&&held.has('kick')?(player.lastAction==='kick'?'strike':'kick'):held.has('kick')?'kick':'strike');if(held.has('chi'))chi();if(held.has('spell'))cast();
 for(const e of [...enemies]){updateEnemy(e,dt);if(mode!=='playing')break;}enemies=enemies.filter(e=>!e.remove);if(mode!=='playing'){updateHUD();return;}
 for(const p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.owner==='player'){for(const e of enemies)if(!e.dead&&!p.hits.includes(e.id)&&Math.abs(p.x-e.x)<p.r+24&&Math.abs(p.y-e.y)<38){p.hits.push(e.id);damageEnemy(e,p.damage,15,{breakGuard:true});if(p.kind==='fire')e.burn=3;if(!p.pierce)p.life=0;}}else if(Math.abs(p.x-player.x)<p.r+18&&Math.abs(p.y-player.y)<35&&player.z<45){hurtPlayer(p.damage,p.x);if(p.kind==='frost')player.slow=2.5;if(p.kind==='venom')hazard(p.x,p.y,36,'poison',0,2,6);p.life=0;}}
 projectiles=projectiles.filter(p=>p.life>0&&p.x>-100&&p.x<length()+100&&p.y>320&&p.y<580);for(const h of hazards){if(h.delay>0){h.delay-=dt;continue;}h.life-=dt;h.tick-=dt;if(h.tick<=0){h.tick=h.kind==='poison'?.65:.5;if(Math.abs(player.x-h.x)<h.r&&Math.abs(player.y-h.y)<h.r*.55+12){hurtPlayer(h.damage,h.x);if(h.kind==='poison')player.slow=.8;}}}hazards=hazards.filter(h=>h.life>0);
 for(const d of drops){d.life-=dt;if(Math.abs(player.x-d.x)<36&&Math.abs(player.y-d.y)<34)pickup(d);}drops=drops.filter(d=>d.life>0);for(const e of effects){e.life-=dt;if(e.type==='spark'){e.x+=e.vx*dt;e.y+=e.vy*dt;e.vy+=420*dt;}}effects=effects.filter(e=>e.life>0);if(!enemies.some(e=>!e.dead)&&!bossSpawned){if(wave<chapter().waves&&player.x>encounterAt(wave))spawnWave();else if(wave===chapter().waves&&player.x>length()-700)spawnBoss();}camera=clamp(player.x-W*.35,0,Math.max(0,length()-W));updateHUD();}
function updateHUD(){if(!player)return;$('health-fill').style.width=clamp(player.hp/player.maxHP*100,0,100)+'%';$('chi-fill').style.width=player.chi+'%';$('mana-fill').style.width=player.mana+'%';$('run-time').textContent=`${Math.floor(stageElapsed/60)}:${String(Math.floor(stageElapsed%60)).padStart(2,'0')}`;$('time-bonus').textContent=`+${timeBonus()}`;$('lives').textContent='◆'.repeat(Math.max(0,player.lives));$('stage-number').textContent=`עולם ${chapter().world+1} · זירה ${chapter().part+1} מתוך 3`;$('stage-name').textContent=chapter().name;$('score').textContent=String(score).padStart(6,'0');$('weapon-btn').textContent=`⚔ ${D.weapons[player.weapon].name}`;$('spell-cycle-btn').textContent=player.spell?`✦ ${D.spells[player.spell].name} ${player.spellRanks[player.spell]||1}`:'✦ —';$('rank-label').textContent=`דרגה ${player.rank} · ${player.gold} זהב`;$('journey-fill').style.width=clamp(player.x/length()*100,0,100)+'%';const boss=enemies.find(e=>e.boss&&!e.dead);$('boss-hud').hidden=!boss;if(boss){$('boss-name').textContent=D.bosses[boss.bossId].name+' · דרגה '+boss.rank+' · שלב קרב '+bossCombatPhase(boss);$('boss-fill').style.width=clamp(boss.hp/boss.maxHP*100,0,100)+'%';}}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function glow(x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
function text(value,x,y,size=12,color='#e5d7b7'){ctx.fillStyle=color;ctx.font=`${size}px "Segoe UI",Arial`;ctx.textAlign='center';ctx.fillText(value,x,y);}
function drawIcon(type,key,x,y,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.lineWidth=2;ctx.lineCap='round';const color=type==='spell'?D.spells[key].color:type==='weapon'?D.weapons[key].color:type==='hp'?'#e5a491':type==='chi'?'#9fd9d1':'#e2c782';ctx.strokeStyle=color;ctx.fillStyle=color;
 if(type==='weapon'){MonkGear.draw(ctx,key,0,0,36,45);}
 else if(type==='spell'){if(key==='lightning'){ctx.beginPath();ctx.moveTo(3,-17);ctx.lineTo(-8,2);ctx.lineTo(1,0);ctx.lineTo(-2,17);ctx.lineTo(10,-4);ctx.lineTo(2,-3);ctx.closePath();ctx.fill();}else if(key==='frost'){for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-14);ctx.moveTo(0,-7);ctx.lineTo(5,-11);ctx.moveTo(0,-7);ctx.lineTo(-5,-11);ctx.stroke();}}else if(key==='earth'){ctx.beginPath();ctx.moveTo(-12,-13);ctx.lineTo(12,-13);ctx.lineTo(10,7);ctx.lineTo(0,17);ctx.lineTo(-10,7);ctx.closePath();ctx.stroke();}else{ctx.beginPath();ctx.moveTo(0,-17);ctx.bezierCurveTo(17,2,13,16,0,16);ctx.bezierCurveTo(-15,13,-12,0,0,-17);ctx.fill();}}
 else if(type==='hp'){ctx.fillRect(-3,-11,6,22);ctx.fillRect(-11,-3,22,6);}else if(type==='chi'){ctx.beginPath();ctx.roundRect(-8,-8,16,22,5);ctx.fill();ctx.fillRect(-4,-15,8,8);}else ellipse(0,0,11,14,color);ctx.restore();}
function enemyEquipment(e,x,y,scale){
 const def=D.enemies[e.type],weapon=e.boss?D.bosses[e.bossId].weapon:def.weapon,pose=e.wind>0?'wind':e.attack>0?'strike':e.stun>0?'idle':'walk';
 ctx.save();if(e.dead)ctx.globalAlpha=Math.min(1,e.dead*2);ctx.translate(x,e.y);ctx.scale(e.dir*scale,scale);
 const hand=MonkArt.hand(1,pose),progress=e.attack>0?1-e.attack/(e.boss?.35:.32):0;
 MonkGear.combat(ctx,weapon,hand[0],hand[1],{active:e.attack>0,wind:e.wind>0,progress,reach:e.boss?150:def.range,enemy:true});
 if(e.type==='shield'||e.guard>0)MonkGear.draw(ctx,'shield',-15,-65,43,66);
 ctx.restore();
}
function drawEnemy(e){const x=e.x-camera;if(x<-240||x>W+240)return;const def=D.enemies[e.type],scale=e.boss?D.bosses[e.bossId].scale:def.scale*(1+(e.rank-1)*.07);ellipse(x,e.y,scale*23,scale*7,'#07101766');ctx.save();if(e.dead)ctx.globalAlpha=e.dead*2;ctx.filter=`hue-rotate(${e.boss?(e.bossId*29)%360:def.hue}deg)`;MonkArt.fighter(ctx,1,x,e.y,e.dir,e.wind>0?'wind':e.attack>0?'strike':e.stun>0?'idle':'walk',scale,time,e.flash>0);ctx.restore();enemyEquipment(e,x,e.y,scale);if(e.burn>0)glow(x,e.y-60,37,'#ee854c44');if(e.slow>0)glow(x,e.y-70,50,'#6fd3e944');if(e.guard>0){ctx.strokeStyle='#a0dbef99';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,e.y-70,40*scale,70*scale,0,0,Math.PI*2);ctx.stroke();}if(!e.boss&&!e.dead){if(e.hp<e.maxHP){ctx.fillStyle='#142130';ctx.fillRect(x-24,e.y-131*scale,48,3);ctx.fillStyle='#d4b987';ctx.fillRect(x-24,e.y-131*scale,48*e.hp/e.maxHP,3);}}if(e.wind>0){text('!',x,e.y-158*scale,23,'#ffe0a3');}}
function drawHeldWeapon(x,pose){
 if(player.dodge>0)return;
 ctx.save();ctx.translate(x,player.y-player.z);ctx.scale(player.dir*1.18,1.18);if(pose==='kick'){const extension=Math.sin(Math.PI*Math.max(0,Math.min(1,1-player.kick/.3)));ctx.translate(extension*12,-extension*9);ctx.rotate(extension*.12);}
 const hand=MonkArt.hand(0,pose),active=pose==='attack',progress=active?1-player.attack/player.attackDuration:0;
 MonkGear.combat(ctx,player.weapon,hand[0],hand[1],{active,progress,reach:D.weapons[player.weapon].range/1.18});ctx.restore();
}
function drawPlayer(){const x=player.x-camera;ellipse(x,player.y,25,8,'#07111b77');ctx.save();if(player.inv>0&&Math.floor(time*13)%2===0)ctx.globalAlpha=.68;const pose=player.kick>0?'kick':player.attack>0?'attack':player.z>0?'jump':held.has('left')||held.has('right')||held.has('up')||held.has('down')?'walk':'idle';if(player.dodge>0){ctx.translate(x,player.y-player.z-38);ctx.rotate(player.dir*(1-player.dodge/.3)*Math.PI*2);MonkArt.fighter(ctx,0,0,38,player.dir,'jump',1.18,time);}else MonkArt.fighter(ctx,0,x,player.y-player.z,player.dir,pose,1.18,time,false,player.kick);ctx.restore();drawHeldWeapon(x,pose);if(player.shield>0){ctx.strokeStyle='#dbc89aaa';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,player.y-65,37,79,0,0,Math.PI*2);ctx.stroke();}if(player.special>0)glow(x,player.y-60,100,'#8ec8a144');}
function drawChest(chest){const x=chest.x-camera;if(x<-70||x>W+70)return;ctx.save();ctx.translate(x,chest.y);ellipse(0,0,27,5,'#05101966');const wood=ctx.createLinearGradient(0,-34,0,0);wood.addColorStop(0,'#a6814e');wood.addColorStop(.5,'#715133');wood.addColorStop(1,'#302924');ctx.fillStyle=wood;ctx.strokeStyle='#443729';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(-22,-27,44,26,3);ctx.fill();ctx.stroke();for(let y=-24;y<-2;y+=6){ctx.strokeStyle='#2a241e66';ctx.beginPath();ctx.moveTo(-20,y);ctx.lineTo(20,y);ctx.stroke();}ctx.fillStyle=wood;ctx.beginPath();ctx.roundRect(-23,chest.opened?-45:-36,46,12,[5,5,2,2]);ctx.fill();ctx.stroke();const brass=ctx.createLinearGradient(-22,-30,22,-10);brass.addColorStop(0,'#ebd49b');brass.addColorStop(.5,'#8e784a');brass.addColorStop(1,'#d2b375');ctx.fillStyle=brass;for(const side of [-1,1]){ctx.fillRect(side*16-2,-27,4,25);for(let y=-24;y<-4;y+=9)ellipse(side*16,y,1,1,'#f4dba6');}ctx.fillRect(-4,-24,8,10);ellipse(0,-18,1,2,'#352e22');if(!chest.opened){glow(0,-29,30,'#b9984522');}ctx.restore();}
function drawHazard(h){const x=h.x-camera,color={poison:'#aad96d',mine:'#efbc79',meteor:'#f3a063',lightning:'#d4bcff',shock:'#e6c8a0'}[h.kind]||'#e2b17d';ctx.save();ctx.strokeStyle=color;ctx.lineWidth=h.delay>0?1.5:3;ctx.globalAlpha=h.delay>0?.45+.25*Math.sin(time*10):.65;ctx.beginPath();ctx.ellipse(x,h.y,h.r,h.r*.26,0,0,Math.PI*2);ctx.stroke();if(h.delay<=0){glow(x,h.y-15,h.r,color+'55');if(h.kind==='meteor')ellipse(x,h.y-22,20,20,color);if(h.kind==='lightning'){ctx.beginPath();ctx.moveTo(x+10,h.y-240);ctx.lineTo(x-14,h.y-155);ctx.lineTo(x+8,h.y-150);ctx.lineTo(x-8,h.y-10);ctx.stroke();}if(h.kind==='poison')ellipse(x,h.y,h.r,h.r*.26,color+'55');}ctx.restore();}
function render(){if(!W)return;ctx.save();if(shake>0)ctx.translate(Math.sin(time*91)*shake,Math.cos(time*77)*shake*.4);const title=mode==='title';MonkArt.background(ctx,title?0:chapter().world,title?120:camera,W,H,time,title?4400:length());if(title){const x=W>680?W*.29:W*.34;MonkArt.fighter(ctx,0,x,H*.85,1,'idle',1.9,time);MonkArt.fighter(ctx,1,x+110,H*.87,-1,'idle',1.2,time);ctx.restore();return;}
 for(const e of enemies)if(e.boss&&!e.dead&&e.wind>0){
  const x=e.x-camera,tx=(e.targetX??player.x)-camera,ty=e.targetY??player.y;
  if(e.skill==='charge'){ctx.save();ctx.strokeStyle='#f3be76';ctx.globalAlpha=.2;ctx.lineWidth=160;ctx.beginPath();ctx.moveTo(x,e.y);ctx.lineTo(x+(e.aimDir||e.dir)*180,clamp(e.y+clamp(ty-e.y,-83,83),380,540));ctx.stroke();ctx.restore();}
  else if(['slam','guard','flame','warcry','pull'].includes(e.skill))drawHazard({x:e.x,y:e.y,r:e.skill==='warcry'?205:e.skill==='pull'?160:e.skill==='slam'&&bossCombatPhase(e)===3?185:135,kind:'shock',delay:e.wind});
  else if(['poison','lightning','meteor','mines','royal'].includes(e.skill))drawHazard({x:e.targetX??player.x,y:ty,r:70,kind:e.skill==='royal'?'meteor':e.skill,delay:e.wind});
 }
 for(const h of hazards)drawHazard(h);for(const chest of chests)drawChest(chest);for(const d of drops){const x=d.x-camera;if(x<-50||x>W+50)continue;const y=d.y-23+Math.sin(time*4+d.id)*3;glow(x,y,26,(d.type==='spell'?D.spells[d.key].color:d.type==='weapon'?D.weapons[d.key].color:'#c4d1a0')+'44');drawIcon(d.type,d.key,x,y,.82);}
 const actors=enemies.map(e=>({y:e.y,draw:()=>drawEnemy(e)}));actors.push({y:player.y,draw:drawPlayer});actors.sort((a,b)=>a.y-b.y).forEach(a=>a.draw());for(const p of projectiles){const x=p.x-camera;if(x<-70||x>W+70)continue;ctx.save();ctx.globalCompositeOperation='lighter';if(p.kind==='arrow'){ctx.strokeStyle=p.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-Math.sign(p.vx)*20,p.y-66);ctx.lineTo(x+Math.sign(p.vx)*8,p.y-66);ctx.stroke();}else{glow(x,p.y-65,p.r*2,p.color+'aa');ellipse(x,p.y-65,p.r*.55,p.r*.65,p.color);}ctx.restore();}for(const e of effects){if(e.type==='bolt'){ctx.save();ctx.strokeStyle=e.col;ctx.shadowColor=e.col;ctx.shadowBlur=10;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(e.x-camera,e.y);ctx.lineTo((e.x+e.tx)/2-camera+Math.sin(time*80)*14,(e.y+e.ty)/2-18);ctx.lineTo(e.tx-camera,e.ty);ctx.stroke();ctx.restore();}else MonkArt.effect(ctx,e,camera);}if(combo>1&&comboTime>0){text(`${combo} HIT`,64,153,25,'#e7c88c');}if(!enemies.some(e=>!e.dead)&&!bossSpawned&&mode==='playing'){const target=wave<chapter().waves?encounterAt(wave)+20:length()-670,x=Math.min(W-70,target-camera);if(x>player.x-camera+45)text('➜',x,315+Math.sin(time*4)*4,30,'#f0d4a1');}ctx.restore();}
function resize(){const r=canvas.parentElement.getBoundingClientRect();W=Math.round(H*r.width/r.height);const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;if(player&&mode!=='title')camera=clamp(player.x-W*.35,0,Math.max(0,length()-W));render();}
new ResizeObserver(resize).observe(canvas.parentElement);
addEventListener('keydown',e=>{if(!$('menu-sheet').hidden){if(e.code==='Escape')$('sheet-close').click();return;}const action=MonkControls.action(e.code);if(action){e.preventDefault();if(mode==='playing'&&!['pause','fullscreen','weapon','magic'].includes(action))press(action);}if(e.repeat)return;if(e.code==='Enter'){if(mode==='title')start();else if(['paused','stageclear','win','gameover'].includes(mode))$('continue-btn').click();}if(action==='pause'||e.code==='Escape')pause();if(action==='weapon'&&mode==='playing')cycleWeapon();if(action==='magic'&&mode==='playing')cycleSpell();if(action==='fullscreen')fullscreen();});addEventListener('keyup',e=>{const action=MonkControls.action(e.code);if(action)release(action);});addEventListener('blur',()=>{clearInput();if(mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});addEventListener('pagehide',saveRun);
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='playing')return;initAudio();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.key);press(b.dataset.key);b.classList.add('pressed');});const releasePointer=e=>{const key=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(![...pointers.values()].includes(key))release(key);b.classList.remove('pressed');};for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,releasePointer);});
$('start-btn').onclick=()=>start();$('pause-btn').onclick=pause;$('continue-btn').onclick=()=>{if(mode==='paused')pause();else if(mode==='gameover')resume();else if(mode==='stageclear'){level++;loadStage();}else start();};$('home-btn').onclick=()=>{saveRun();mode='title';clearInput();for(const id of ['modal','hud','loadout-hud','journey-progress','boss-hud','touch-controls','toast'])$(id).hidden=true;$('title-screen').hidden=false;window.refreshPremiumMenu?.();};$('weapon-btn').onclick=()=>{if(mode==='playing')cycleWeapon();};$('spell-cycle-btn').onclick=()=>{if(mode==='playing')cycleSpell();};$('sound-btn').onclick=()=>{muted=!muted;initAudio();$('sound-btn').textContent=muted?'♫̸':'♪';$('sound-btn').setAttribute('aria-label',muted?'הפעלת צליל':'השתקת צליל');};async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('game-frame').requestFullscreen();}catch{toast('אפשר לשחק גם בחלון רגיל',1);}}$('fullscreen-btn').onclick=fullscreen;
window.MonkGame={profile:()=>({unlocked:profile.unlocked,difficulty:profile.difficulty,hasSave:!!profile.save,savedStage:(profile.save?.level||0)+1,savedWorld:Math.floor((profile.save?.level||0)/3)+1,savedScore:profile.save?.score||0,checkpointWorld:profile.checkpoint?profile.checkpoint.level/3+1:null}),setDifficulty:d=>{if(['story','warrior','master'].includes(d)){profile.difficulty=d;store();}},resume,startLevel:i=>{if(i>=0&&i<profile.unlocked)start(i);},inventory:()=>{const p=(mode==='title'?profile.save?.player:player)||newPlayer();return {weapon:p.weapon||'staff',weapons:p.weapons||['staff'],spell:p.spell,spells:p.spells||[],spellRanks:p.spellRanks||{},rank:p.rank||1,gold:p.gold||0};},equip:(kind,key)=>{const p=player&&mode!=='title'?player:profile.save?.player;if(!p)return;if(kind==='weapon'&&p.weapons?.includes(key))p.weapon=key;if(kind==='spell'&&p.spells?.includes(key))p.spell=key;if(['playing','paused'].includes(mode))saveRun();else store();updateHUD();},pauseForMenu:()=>{if(mode==='playing')pause();},content:D};
window.render_game_to_text=()=>JSON.stringify({mode,coordinates:'origin top-left; x right, y down; z jump height; walkable y 380–540',world:chapter().world+1,substage:chapter().part+1,stage:level+1,totalStages:15,worldName:world().name,stageName:chapter().name,worldWidth:length(),difficulty,wave,totalWaves:chapter().waves,bossSpawned,score,stageElapsed,timeBonus:timeBonus(),lastTimeBonus,best,combo,comboName,unlocked:profile.unlocked,hasSave:!!profile.save,checkpoint:profile.checkpoint?{world:profile.checkpoint.level/3+1,stage:profile.checkpoint.level+1,score:profile.checkpoint.score}:null,camera:Math.round(camera),viewport:{w:W,h:H},player:player?{x:Math.round(player.x),y:Math.round(player.y),z:Math.round(player.z),hp:player.hp,maxHP:player.maxHP,chi:Math.round(player.chi),mana:Math.round(player.mana),running:!!runDirection,lives:player.lives,dir:player.dir,rank:player.rank,xp:player.xp,gold:player.gold,weapon:player.weapon,weapons:player.weapons,spell:player.spell,spells:player.spells,spellRanks:player.spellRanks,shield:player.shield,dodge:player.dodge,dodgeCooldown:player.dodgeCD,attack:player.attack,kick:player.kick,cooldown:player.cooldown,castCooldown:player.castCD,inv:player.inv,slow:player.slow}:null,enemies:enemies.map(e=>({id:e.id,x:Math.round(e.x),y:Math.round(e.y),hp:e.hp,maxHP:e.maxHP,boss:e.boss,type:e.type,rank:e.rank,weapon:e.boss?D.bosses[e.bossId].weapon:D.enemies[e.type].weapon,damage:e.damage,name:e.boss?D.bosses[e.bossId].name:D.enemies[e.type].name,bossId:e.bossId,skill:e.skill,combatPhase:e.boss?bossCombatPhase(e):undefined,target:e.boss&&e.wind>0?{x:Math.round(e.targetX??player.x),y:Math.round(e.targetY??player.y)}:undefined,recovery:e.recovery||0,telegraph:e.wind>0,guard:e.guard,slow:e.slow,burn:e.burn,dead:e.dead>0})),chests:chests.map(c=>({x:Math.round(c.x),y:c.y,opened:c.opened,hp:c.hp,items:c.items})),drops:drops.map(d=>({x:Math.round(d.x),y:d.y,type:d.type,key:d.key})),projectiles:projectiles.map(p=>({x:Math.round(p.x),y:Math.round(p.y),owner:p.owner,kind:p.kind})),hazards:hazards.map(h=>({x:Math.round(h.x),y:h.y,r:h.r,kind:h.kind,warning:h.delay>0})),nextWaveAt:wave<chapter().waves?encounterAt(wave):length()-700,artLoaded:!!MonkArt.atlas.naturalWidth});
window.advanceTime=ms=>{manual=true;for(let i=0;i<Math.ceil(ms/(1000/60));i++)update(1/60);render();};function loop(ts){const dt=Math.min((ts-lastFrame)/1000,.035);lastFrame=ts;if(!manual)update(dt);render();requestAnimationFrame(loop);}$('best-score').textContent=String(best).padStart(6,'0');resize();requestAnimationFrame(loop);
})();


