(() => {
const $=id=>document.getElementById(id);
const sheet=$('menu-sheet');
const D=MonkContent;
function api(){return window.MonkGame;}
function close(){sheet.hidden=true;MonkControls.cancel();}
function show(title,body){$('sheet-title').textContent=title;$('sheet-body').replaceChildren(body);sheet.hidden=false;}
function levels(worldIndex){const p=api().profile();if(!Number.isInteger(worldIndex))worldIndex=p.hasSave?p.savedWorld-1:Math.floor((p.unlocked-1)/3);const box=document.createElement('div'),tabs=document.createElement('div');tabs.className='world-tabs';D.worlds.forEach((w,i)=>{const b=document.createElement('button');b.textContent=`${i+1} · ${w.name}`;b.className=i===worldIndex?'selected':'';b.onclick=()=>levels(i);tabs.append(b);});const grid=document.createElement('div');grid.className='level-grid';D.chapters.filter(c=>c.world===worldIndex).forEach(c=>{const b=document.createElement('button');b.className='level-card';b.disabled=c.id>=p.unlocked;b.style.backgroundImage=`linear-gradient(0deg,#0b1826ed,transparent),url("${MonkArt.thumbnail(worldIndex)}")`;b.innerHTML=`<span>זירה ${worldIndex+1}.${c.part+1} ${b.disabled?'· נעולה':'· פתוחה'} · ${c.length} יחידות</span><b>${c.name}</b><small>${c.boss.name}</small><span class="boss-description">${c.boss.description} · ${c.boss.hp} חיים</span>`;b.onclick=()=>{close();api().startLevel(c.id);};grid.append(b);});const hint=document.createElement('p');hint.className='sheet-hint';hint.textContent='5 עולמות · 15 זירות · 15 בוסים. כל ניצחון פותח את הזירה הבאה. הציוד עובר איתך בין הזירות במסע.';box.append(tabs,grid,hint);show('מפת המסע',box);}
function settings(){const box=document.createElement('div');box.className='settings-content';const profile=api().profile();const label=document.createElement('p');label.textContent='רמת קושי';box.append(label);const options=document.createElement('div');options.className='difficulty-options';[['story','מסע','לחימה סלחנית, יותר חיים'],['warrior','לוחם','האיזון המומלץ'],['master','מאסטר','אויבים קשוחים ומכות כבדות']].forEach(([id,name,desc])=>{const b=document.createElement('button');b.className=profile.difficulty===id?'selected':'';b.innerHTML=`<b>${name}</b><small>${desc}</small>`;b.onclick=()=>{api().setDifficulty(id);settings();};options.append(b);});box.append(options);const p=document.createElement('p');p.className='sheet-hint';p.textContent='רמת הקושי תחול במסע חדש או בבחירת שלב. המסע השמור ממשיך ברמת הקושי המקורית.';box.append(p);const sound=document.createElement('button');sound.className='menu-link';sound.textContent='הפעלת / השתקת צלילי קרב';sound.onclick=()=>$('sound-btn').click();box.append(sound);box.append(MonkControls.panel());show('הגדרות',box);}
function guide(){const box=document.createElement('div');box.className='guide-content';box.innerHTML='<p>ארבעה מארבים ובוס בכל זירה. שבור תיבות ואסוף נשקים, קסמים וקמעות. מגנים נפרצים באמצעות בעיטה או פטיש.</p><table class="combo-table"><tbody>'+D.combos.map(c=>`<tr><td>${c.name}</td><td>${c.keys.map(k=>k==='kick'?'בעיטה':'מכה').join(' ← ')}</td></tr>`).join('')+'<tr><td>בעיטת השמיים</td><td>קפיצה ← בעיטה</td></tr><tr><td>מכת הצל</td><td>גלגול ← מכה</td></tr></tbody></table><dl><dt>מכה A / J · בעיטה X / U</dt><dd>בצע את הרצף תוך 1.7 שניות בין מכות. לחיצה כפולה והחזקה של כיוון מפעילה ריצה, גם לאחור. החזקה של שני הכפתורים מחליפה בין מכה לבעיטה.</dd><dt>קסם Q / E · החלפת קסם V</dt><dd>מד הקסם הסגול מתמלא עם הזמן; צ׳י ירוק מפעיל גל הדף סביב הנזיר. מצא מגילות. קסם כפול משדרג את עוצמתו עד דרגה 3. לחץ על שם הקסם בממשק כדי להחליף בנייד.</dd><dt>החלפת נשק C · צ׳י B / K</dt><dd>לחץ על שם הנשק בנייד. חנית ארוכה, שרשרת מהירה, מוט מצית ופטיש שובר שריון.</dd><dt>גלגול L / Shift · קפיצה רווח</dt><dd>התחמק מטווחי ההתרעה, קליעים, רעל וברקים. השהיה P שומרת את הקרב.</dd></dl>';show('קומבואים ואומנות הלחימה',box);}
function inventory(){api().pauseForMenu();const inv=api().inventory(),box=document.createElement('div');function section(title,items,owned,selected,kind){const h=document.createElement('h3');h.className='collection-title';h.textContent=title;box.append(h);const grid=document.createElement('div');grid.className='collection-grid';Object.entries(items).forEach(([key,item])=>{const b=document.createElement('button');b.className='collection-card'+(key===selected?' selected':'');b.disabled=!owned.includes(key);b.innerHTML=`<b>${item.name}${kind==='spell'&&owned.includes(key)?' · '+(inv.spellRanks[key]||1):''}</b><small>${item.description}</small><small>${b.disabled?'נמצא בתיבות ובשלל':key===selected?'מצויד כרגע':'לחץ כדי לצייד'}</small>`;if(kind==='weapon')b.prepend(MonkGear.preview(key));b.onclick=()=>{api().equip(kind,key);inventory();};grid.append(b);});box.append(grid);}section('נשקים',D.weapons,inv.weapons,inv.weapon,'weapon');section('קסמים',D.spells,inv.spells,inv.spell,'spell');const p=document.createElement('p');p.className='sheet-hint';p.textContent=`דרגת נזיר ${inv.rank} · ${inv.gold} זהב. הציוד שנאסף ורמות הקסמים נשמרים לאורך המסע.`;box.append(p);show('ציוד וקסמים',box);}
$('levels-btn').onclick=levels;$('settings-btn').onclick=settings;$('guide-btn').onclick=guide;$('sheet-close').onclick=close;$('resume-btn').onclick=()=>api().resume();
$('inventory-btn').onclick=inventory;const collection=document.createElement('button');collection.textContent='ציוד וקסמים';collection.onclick=inventory;document.querySelector('.menu-row').append(collection);document.querySelector('.title-meta').children[2].textContent='15 בוסים';
document.querySelectorAll('.chapter').forEach((el,i)=>{el.tabIndex=0;el.setAttribute('role','button');el.querySelector('small').textContent='3 זירות · 3 בוסים';el.onclick=()=>levels(i);el.onkeydown=e=>{if(e.key==='Enter')el.click();};});
document.querySelector('.controls').insertAdjacentHTML('beforeend','<span><kbd>X / U</kbd> בעיטה</span><span><kbd>Q / E</kbd> קסם</span><span><kbd>C / V</kbd> החלפת ציוד</span><span><kbd>L</kbd> גלגול</span>');
window.refreshPremiumMenu=()=>{const p=api().profile();$('resume-btn').hidden=!p.hasSave;$('save-label').textContent=p.hasSave?`מסע שמור · עולם ${p.savedWorld} · זירה ${(p.savedStage-1)%3+1} · ${p.savedScore.toLocaleString('he-IL')} נקודות`:'המסע שלך יישמר אוטומטית';$('difficulty-label').textContent={story:'מסע',warrior:'לוחם',master:'מאסטר'}[p.difficulty];};
refreshPremiumMenu();MonkControls.refresh();const bindingsButton=document.createElement("button");bindingsButton.className="secondary";bindingsButton.textContent="הגדרות ומקשים";bindingsButton.onclick=settings;document.querySelector(".modal-card").append(bindingsButton);
})();
