const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{
fs.mkdirSync('output/expansion',{recursive:true});const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1040}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://localhost:5173');await page.waitForFunction(()=>MonkArt.atlas.naturalWidth>0&&MonkArt.environments.every(i=>i.naturalWidth>0));
await page.screenshot({path:'output/expansion/title.png',fullPage:true});await page.click('#levels-btn');assert.equal(await page.locator('.level-card').count(),3);assert.equal(await page.locator('.level-card:disabled').count(),2);await page.locator('.world-tabs button').nth(4).click();assert.equal(await page.locator('.level-card:disabled').count(),3);await page.screenshot({path:'output/expansion/map.png',fullPage:true});await page.click('#sheet-close');
await page.evaluate(()=>MonkGame.setDifficulty('story'));await page.click('#start-btn');
const combos=await page.evaluate(()=>{const key=(code,on)=>dispatchEvent(new KeyboardEvent(on?'keydown':'keyup',{code}));const observed=[];for(const codes of [['KeyA','KeyA','KeyX'],['KeyA','KeyX','KeyA'],['KeyX','KeyA','KeyX'],['KeyX','KeyX','KeyA']]){advanceTime(1900);for(const code of codes){key(code,true);advanceTime(1);key(code,false);observed.push(JSON.parse(render_game_to_text()).comboName);advanceTime(480);}}return observed;});assert(combos.includes('עקב הדרקון'));assert(combos.includes('מערבולת המוט'));assert(combos.includes('סופת הלוטוס'));assert(combos.includes('שובר השריון'));
await page.reload();await page.click('#start-btn');
const results=[],seenTypes=new Set(),seenRanks=new Set(),seenSkills=new Set();
for(let stage=1;stage<=15;stage++){
 let watched=false,finished=false;
 for(let batch=0;batch<90;batch++){
 const r=await page.evaluate(()=>{
  const get=()=>JSON.parse(render_game_to_text());let prev=new Set();const seen={types:[],ranks:[],skills:[]};
  function keys(list){const next=new Set(list);for(const k of prev)if(!next.has(k))dispatchEvent(new KeyboardEvent('keyup',{code:k}));for(const k of next)if(!prev.has(k))dispatchEvent(new KeyboardEvent('keydown',{code:k}));prev=next;}
  for(let i=0;i<100;i++){
   const s=get();if(s.mode!=='playing'){keys([]);return {state:s,seen};}
   s.enemies.forEach(e=>{seen.types.push(e.type);seen.ranks.push(e.rank);if(e.skill)seen.skills.push(e.skill);});
   const living=s.enemies.filter(e=>!e.dead),nearest=living.sort((a,b)=>Math.abs(a.x-s.player.x)-Math.abs(b.x-s.player.x))[0];
   let target=nearest;
   if(!living.length){const loot=s.drops.filter(d=>Math.abs(d.x-s.player.x)<300).sort((a,b)=>Math.abs(a.x-s.player.x)-Math.abs(b.x-s.player.x))[0];const chest=s.chests.filter(c=>!c.opened&&c.x>s.player.x-180).sort((a,b)=>a.x-b.x)[0];if(loot)target={...loot,loot:true};else if(chest&&chest.x<s.nextWaveAt+200)target={...chest,chest:true};}
   const list=['KeyA','KeyX'];if(living.length)list.push('Space');
   if(target){const dx=target.x-s.player.x,dy=target.y-s.player.y,stop=target.loot?8:target.chest?48:50;if(Math.abs(dx)>stop)list.push(dx>0?'ArrowRight':'ArrowLeft');else if(!target.loot&&Math.sign(dx)!==s.player.dir&&Math.abs(dx)>2)list.push(dx>0?'ArrowRight':'ArrowLeft');if(Math.abs(dy)>9)list.push(dy>0?'ArrowDown':'ArrowUp');if(!target.loot&&!target.chest&&s.player.chi>78&&Math.abs(dx)<150)list.push('KeyB');if(s.player.spell&&living.length&&s.player.chi>35&&Math.abs(dx)<260)list.push('KeyQ');}else list.push('ArrowRight');
   keys(list);advanceTime(100);if(!s.bossSpawned&&get().bossSpawned){keys([]);return {state:get(),seen,bossArrival:true};}
  }
  keys([]);return {state:get(),seen};
 });
 r.seen.types.forEach(x=>seenTypes.add(x));r.seen.ranks.forEach(x=>seenRanks.add(x));r.seen.skills.forEach(x=>seenSkills.add(x));
 if(r.bossArrival&&!watched){watched=true;const observations=await page.evaluate(()=>{const skills=[],hazards=[],projectiles=[];dispatchEvent(new KeyboardEvent('keydown',{code:'Space'}));for(let i=0;i<70;i++){advanceTime(200);const s=JSON.parse(render_game_to_text());const b=s.enemies.find(e=>e.boss);if(b?.skill)skills.push(b.skill);hazards.push(...s.hazards.map(h=>h.kind));projectiles.push(...s.projectiles.map(p=>p.kind));}dispatchEvent(new KeyboardEvent('keyup',{code:'Space'}));return {skills,hazards,projectiles,state:JSON.parse(render_game_to_text())};});observations.skills.forEach(x=>seenSkills.add(x));await page.screenshot({path:`output/expansion/boss-${stage}.png`,fullPage:true});assert.equal(observations.state.mode,'playing');}
 if(r.state.mode!=='playing'){assert.equal(r.state.mode,stage===15?'win':'stageclear',`stage ${stage}: ${JSON.stringify(r.state)}`);results.push({stage,world:r.state.world,substage:r.state.substage,score:r.state.score,hp:r.state.player.hp,lives:r.state.player.lives,inventory:r.state.player.weapons,spells:r.state.player.spells});finished=true;break;}
 if(batch===89)throw new Error(`Stage ${stage} stuck: ${JSON.stringify(r.state)}`);
 }
 assert(finished);console.log(`stage ${stage} cleared`);
 if(stage===1){await page.click('#continue-btn');const before=await page.evaluate(()=>{advanceTime(1);document.getElementById('pause-btn').click();return JSON.parse(render_game_to_text());});await page.reload();await page.click('#resume-btn');const after=await page.evaluate(()=>JSON.parse(render_game_to_text()));assert.equal(after.stage,2);assert.deepEqual(after.player.weapons,before.player.weapons);assert.deepEqual(after.player.spells,before.player.spells);assert.deepEqual(after.player.spellRanks,before.player.spellRanks);await page.click('#inventory-btn');await page.screenshot({path:'output/expansion/inventory.png',fullPage:true});await page.click('#sheet-close');await page.click('#continue-btn');}
 else if(stage<15)await page.click('#continue-btn');
}
assert.equal(results.length,15);assert.equal(seenTypes.size,7);assert.equal(seenRanks.size,3);assert(seenSkills.size>=12);assert.equal(results[14].inventory.length,5);assert.equal(results[14].spells.length,4);await page.screenshot({path:'output/expansion/win.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://localhost:5173');await mobile.tap('#start-btn');await mobile.evaluate(()=>advanceTime(1));assert.equal(await mobile.locator('.action-pad button').count(),6);assert(await mobile.locator('[data-key=kick]').isVisible());assert(await mobile.locator('[data-key=spell]').isVisible());await mobile.screenshot({path:'output/expansion/mobile.png',fullPage:true});const a=await mobile.locator('[data-key=right]').boundingBox(),b=await mobile.locator('[data-key=kick]').boundingBox();const cd=await mobile.context().newCDPSession(mobile);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+a.width/2,y:a.y+a.height/2,id:1},{x:b.x+b.width/2,y:b.y+b.height/2,id:2}]});await mobile.evaluate(()=>advanceTime(500));const touch=await mobile.evaluate(()=>JSON.parse(render_game_to_text()));assert(touch.player.x>175);await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.setViewportSize({width:844,height:390});await mobile.screenshot({path:'output/expansion/landscape.png',fullPage:true});assert.deepEqual(errors,[]);fs.writeFileSync('output/expansion/results.json',JSON.stringify({results,seenTypes:[...seenTypes],seenRanks:[...seenRanks],seenSkills:[...seenSkills],combos,errors},null,2));await browser.close();console.log(JSON.stringify({passed:true,stages:15,bosses:15,enemyTypes:seenTypes.size,skills:seenSkills.size,weapons:5,spells:4,saveResume:true,multitouch:true,errors}));
})().catch(e=>{console.error(e);process.exit(1);});
