const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
function fixture(spell,type='grunt',incoming=false){return {version:3,unlocked:15,difficulty:'warrior',save:{combatVersion:2,kind:'battle',level:0,score:0,difficulty:'warrior',player:{x:800,y:465,hp:100,maxHP:100,healthVersion:1,lives:3,dir:1,chi:100,weapon:'staff',weapons:['staff','spear','chain','ember','hammer'],spell,spells:['fire','frost','lightning','earth'],spellRanks:{fire:1,frost:1,lightning:1,earth:1},rank:1,xp:0,gold:0},enemies:[{id:1,type,rank:1,x:885,y:465,hp:200,maxHP:200,dir:-1,boss:false,cooldown:100,wind:0,attack:0,stun:10,flash:0,dead:0,slow:0,burn:0,burnTick:.5,speed:0,damage:7,guard:0},{id:2,type:'grunt',rank:1,x:970,y:465,hp:200,maxHP:200,dir:-1,boss:false,cooldown:100,wind:0,attack:0,stun:10,flash:0,dead:0,slow:0,burn:0,burnTick:.5,speed:0,damage:7,guard:0}],drops:[],chests:[],hazards:[],projectiles:incoming?[{id:90,owner:'enemy',x:1800,y:465,vx:-400,vy:0,kind:'arrow',damage:20,r:9,life:4,color:'#d8c8aa',hits:[]}]:[],wave:4,bossSpawned:false,nextId:100}};}
async function load(data){await page.goto('http://localhost:5173');await page.evaluate(value=>localStorage.setItem('monk-profile-v3',JSON.stringify(value)),data);await page.reload();await page.click('#resume-btn');}
const report={};
for(const spell of ['fire','frost','lightning','earth']){await load(fixture(spell,'grunt',spell==='earth'));const s=await page.evaluate(key=>{dispatchEvent(new KeyboardEvent('keydown',{code:'KeyQ'}));advanceTime(1);dispatchEvent(new KeyboardEvent('keyup',{code:'KeyQ'}));advanceTime(key==='earth'?3100:200);return JSON.parse(render_game_to_text());},spell);report[spell]=s;if(spell==='fire'){assert(s.enemies[0].hp<200);assert(s.enemies[0].burn>0);}if(spell==='frost'){assert(s.enemies[0].slow>3);assert(s.enemies[0].hp<200);}if(spell==='lightning')assert(s.enemies.every(e=>e.hp<200));if(spell==='earth'){assert.equal(s.player.hp,100);assert.equal(s.player.shield,60);}}
const shieldFixture=fixture('fire','shield');shieldFixture.save.enemies[0].x=875;await load(shieldFixture);const guard=await page.evaluate(()=>{dispatchEvent(new KeyboardEvent('keydown',{code:'KeyA'}));advanceTime(1);dispatchEvent(new KeyboardEvent('keyup',{code:'KeyA'}));const blocked=JSON.parse(render_game_to_text()).enemies[0].hp;advanceTime(500);dispatchEvent(new KeyboardEvent('keydown',{code:'KeyX'}));advanceTime(1);dispatchEvent(new KeyboardEvent('keyup',{code:'KeyX'}));const kicked=JSON.parse(render_game_to_text()).enemies[0].hp;return {blocked,kicked};});assert.equal(guard.blocked,193);assert(guard.blocked-guard.kicked>=25);
await load(fixture('fire'));await page.evaluate(()=>MonkGame.equip('weapon','ember'));const burn=await page.evaluate(()=>{dispatchEvent(new KeyboardEvent('keydown',{code:'KeyA'}));advanceTime(1);dispatchEvent(new KeyboardEvent('keyup',{code:'KeyA'}));advanceTime(600);return JSON.parse(render_game_to_text());});assert(burn.enemies[0].burn>0);assert(burn.enemies[0].hp<174);
await page.evaluate(()=>{document.getElementById('pause-btn').click();});const saved=await page.evaluate(()=>JSON.parse(render_game_to_text()));await page.reload();await page.click('#resume-btn');const restored=await page.evaluate(()=>JSON.parse(render_game_to_text()));assert.equal(restored.player.weapon,'ember');assert.deepEqual(restored.player.spellRanks,saved.player.spellRanks);assert.deepEqual(errors,[]);await browser.close();console.log(JSON.stringify({passed:true,fire:'burn + damage',frost:'slow + damage',lightning:'multiple targets',earth:'20 damage absorbed without HP loss',shield:'staff blocked and kick pierced',ember:'burn damage over time',save:'inventory preserved',errors}));})().catch(e=>{console.error(e);process.exit(1);});
