const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('output/weapons',{recursive:true});
function fixture(weapon='staff',type='grunt',dx=80){return {version:3,unlocked:15,difficulty:'warrior',save:{combatVersion:2,kind:'battle',level:0,score:0,difficulty:'warrior',player:{x:800,y:465,hp:100,maxHP:100,lives:3,dir:1,chi:80,mana:80,weapon,weapons:['staff','spear','chain','ember','hammer'],rank:1,xp:0,gold:0},enemies:[{id:1,type,rank:1,x:800+dx,y:465,hp:500,maxHP:500,dir:-1,boss:false,cooldown:100,wind:0,attack:0,stun:100,flash:0,dead:0,slow:0,burn:0,burnTick:.5,speed:0,damage:16,guard:0}],drops:[],chests:[],hazards:[],projectiles:[],wave:4,bossSpawned:true,nextId:100}};}
async function load(f){await page.goto('http://localhost:5173');await page.evaluate(v=>localStorage.setItem('monk-profile-v3',JSON.stringify(v)),f);await page.reload();await page.click('#resume-btn');await page.waitForFunction(()=>MonkArt.atlas.naturalWidth&&MonkGear.ready());await page.evaluate(()=>advanceTime(0));}
const read=()=>page.evaluate(()=>JSON.parse(render_game_to_text()));
async function strike(){return page.evaluate(()=>{dispatchEvent(new KeyboardEvent('keydown',{code:'KeyA'}));advanceTime(1);dispatchEvent(new KeyboardEvent('keyup',{code:'KeyA'}));return JSON.parse(render_game_to_text());});}
const report={};for(const weapon of ['staff','spear','chain','ember','hammer']){await load(fixture(weapon));const s=await strike();report[weapon]={damage:500-s.enemies[0].hp,cooldown:s.player.cooldown,range:await page.evaluate(k=>MonkContent.weapons[k].range,weapon)};assert.equal(report[weapon].damage,await page.evaluate(k=>MonkContent.weapons[k].damage,weapon));await page.evaluate(()=>advanceTime(90));await page.screenshot({path:`output/weapons/${weapon}.png`});if(weapon==='ember')assert((await read()).enemies[0].burn>0);}
assert(report.hammer.damage>report.spear.damage);assert(report.hammer.cooldown>report.chain.cooldown);
for(const [weapon,dx,expected] of [['staff',145,false],['spear',145,true],['hammer',145,false],['chain',-100,true],['spear',-100,false]]){await load(fixture(weapon,'grunt',dx));const s=await strike();assert.equal(s.enemies[0].hp<500,expected,`${weapon}:${dx}`);}
await load(fixture('staff','shield'));let blocked=await strike();assert.equal(blocked.enemies[0].hp,493);await load(fixture('hammer','shield'));let hammer=await strike();assert.equal(hammer.enemies[0].hp,457);assert(hammer.enemies[0].telegraph===false);
const spearEnemy=fixture('staff','scout',125);spearEnemy.save.enemies[0].stun=0;spearEnemy.save.enemies[0].cooldown=1.8;await load(spearEnemy);await page.evaluate(()=>advanceTime(2600));let reach=await read();assert(reach.player.hp<100,'spear enemy must hit at spear range');assert.equal(reach.enemies[0].weapon,'spear');
await load(fixture());await page.click('#pause-btn');const saved=await read();await page.reload();await page.click('#resume-btn');assert.equal((await read()).enemies[0].hp,saved.enemies[0].hp);
const migration=fixture();delete migration.save.combatVersion;migration.save.enemies[0].hp=24;migration.save.enemies[0].maxHP=48;await load(migration);const migrated=await read();assert.equal(migrated.enemies[0].maxHP,62);assert.equal(migrated.enemies[0].hp,31);await page.click('#pause-btn');await page.reload();await page.click('#resume-btn');assert.equal((await read()).enemies[0].hp,31);
await page.evaluate(()=>MonkGame.startLevel(0));const fresh=await read();assert(fresh.enemies.every(e=>e.damage>=10));assert.equal(await page.evaluate(()=>MonkContent.bosses[0].hp),493);assert.equal(await page.evaluate(()=>MonkContent.bosses[0].damage),20);
for(const type of ['archer','shaman','brute','berserker']){await load(fixture('spear',type));await page.evaluate(()=>advanceTime(1));await page.screenshot({path:`output/weapons/enemy-${type}.png`});}
await page.setViewportSize({width:390,height:844});await load(fixture('hammer','brute'));await strike();await page.evaluate(()=>advanceTime(100));await page.screenshot({path:'output/weapons/mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,report,enemySpearRange:true,shield:'hammer breaks; staff blocked',migration:'preserves hp ratio once',errors}));await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
